[jira]
jira_url =https://fundingcircle.atlassian.net
jira_username = juan.vaccari@fundingcircle.com
jira_api_token = ATATT3xFfGF05GbOjCxjIUoC8T-QUnURUzxiqgjMZjER7dTmxoar-O3wnsuCq4twPOguoZUoHhwb1LWpmgxfSy-mKT9PTY277E_nisps04zoQWNwSBGFwByy-rJ8ETJQaExQi99wcLKQ5Tc2ZfRX7hHgAdWO4gYNG8DtJnSFP_aM-0IK5ilDPRE=32E8A6DA
verify_ssl = False

[dates]
start_date = 2026-04-20
end_date = 2026-04-24

[projects]
project_keys = STCP
